M48
; DRILL file {KiCad 7.0.10+dfsg-1} date Thu Feb  8 12:56:09 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-02-08T12:56:09+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X4.7199Y-2.0711
X4.9108Y-2.0711
T2
X4.7081Y-1.9518
X4.9226Y-1.9518
M30
