M48
; DRILL file {KiCad 7.0.10+dfsg-1} date Thu Feb  1 07:38:55 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-02-01T07:38:55+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X5.0949Y-2.9711
X5.2858Y-2.9711
T2
X5.0831Y-2.8518
X5.2976Y-2.8518
M30
